package org.anudip;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.stream.Stream;

import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.condition.DisabledIf;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

@TestInstance(Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class AppTest {
	static Class<?> operationClass;
	static Method operationMethod;
	static int counter1forTest5, counter1forTest6, counter1forTest7,
			   counter2forTest5, counter2forTest6, counter2forTest7,
			   counter3forTest5, counter3forTest6, counter3forTest7;

	@Test
	@Order(1)
	public void test1() {
		boolean isValidPackageAndClassName = true;
				
		try {
			operationClass = Class.forName("org.anudip.javaappassignment02.operation.EvenOddNumber");
		} catch (ClassNotFoundException cnfEx) {
			isValidPackageAndClassName = false;
		} catch (NoClassDefFoundError ncdfErr) {
			isValidPackageAndClassName = false;
		}
		
		assertTrue(isValidPackageAndClassName, "Either the package name or class name does not match with either GUIDELINE 1 or GUIDELINE 2.");
	}

	boolean customConditionForClass() {
		return (operationClass == null) ? true : false;
	}

	@Test
	@Order(2)
	@DisabledIf("customConditionForClass")
	public void test2() {
		boolean isValidMethod = true;
		
		try {
			operationMethod = operationClass.getMethod("defineEvenNumber");
			
			String expectedMethodSyntax = "public java.lang.String org.anudip.javaappassignment02.operation.EvenOddNumber.defineEvenNumber()";
			String actualMethodSyntax = operationMethod.toString();
			
			if (!actualMethodSyntax.equals(expectedMethodSyntax)) {
				isValidMethod = false;
			}
		} catch (NoSuchMethodException nsmEx) {
			isValidMethod = false;
		}
		
		operationMethod = null;
		
		
		assertTrue(isValidMethod, "The method name or syntax does not match with GUIDELINE 3.");
	}
	
	@Test
	@Order(3)
	@DisabledIf("customConditionForClass")
	public void test3() {
		boolean isValidMethod = true;
		
		try {
			operationMethod = operationClass.getMethod("defineOddNumber");
			
			String expectedMethodSyntax = "public java.lang.String org.anudip.javaappassignment02.operation.EvenOddNumber.defineOddNumber()";
			String actualMethodSyntax = operationMethod.toString();
			
			if (!actualMethodSyntax.equals(expectedMethodSyntax)) {
				isValidMethod = false;
			}
		} catch (NoSuchMethodException nsmEx) {
			isValidMethod = false;
		}
		
		operationMethod = null;
		
		assertTrue(isValidMethod, "The method name or syntax does not match with GUIDELINE 4.");
	}

	@Test
	@Order(4)
	@DisabledIf("customConditionForClass")
	public void test4() {
		boolean isValidMethod = true;
		
		try {
			operationMethod = operationClass.getMethod("verifyIfNumberIsEvenOrOdd", Integer.TYPE);
			
			String expectedMethodSyntax = "public java.lang.String org.anudip.javaappassignment02.operation.EvenOddNumber.verifyIfNumberIsEvenOrOdd(int)";
			String actualMethodSyntax = operationMethod.toString();
			
			if (!actualMethodSyntax.equals(expectedMethodSyntax)) {
				isValidMethod = false;
			}
		} catch (NoSuchMethodException nsmEx) {
			isValidMethod = false;
		}
		
		assertTrue(isValidMethod, "The method name or syntax does not match with either GUIDELINE 5 or GUIDELINE 6a, 6b, and 6c.");
	}
	
	boolean customConditionForMethod() {
		return (operationMethod == null) ? true : false;
	}

	static Stream<Arguments> numbersProviderForTest5() {
		return Stream.of(
					Arguments.of(10),
					Arguments.of(9)
				);
	}

	@ParameterizedTest
	@MethodSource({"numbersProviderForTest5"})
	@Order(5)
	@DisabledIf("customConditionForMethod")
	public void test5(int num) {
		int[] sampleInputs = {1, 2};
		int[] parameters1 = {10, 9};
		String[] expectedResults = {"Even Number", "Odd Number"};
		
		try {
			Object classObject = operationClass.getDeclaredConstructor((Class<?>[]) new Class[0]).newInstance(new Object[0]);
			
			String actualResult = (String) operationMethod.invoke(classObject, num);
			
			assertEquals(expectedResults[counter1forTest5++], actualResult, "The result generated by the method does not match with the Expected Output of Sample Input " + sampleInputs[counter2forTest5++] + ": " + parameters1[counter3forTest5++]);
		} catch (InstantiationException | IllegalAccessException | InvocationTargetException | NoSuchMethodException ex) {
		}
	}

	static Stream<Arguments> numbersProviderForTest6() {
		return Stream.of(
					Arguments.of(-10)
				);
	}

	@ParameterizedTest
	@MethodSource({"numbersProviderForTest6"})
	@Order(6)
	@DisabledIf("customConditionForMethod")
	public void test6(int num) {
		int[] sampleInputs = {3};
		int[] parameters1 = {-10};
		String[] expectedResults = {"-1"};
		
		try {
			Object classObject = operationClass.getDeclaredConstructor((Class<?>[]) new Class[0]).newInstance(new Object[0]);
			
			String actualResult = (String) operationMethod.invoke(classObject, num);
			
			assertEquals(expectedResults[counter1forTest6++], actualResult, "The result generated by the method does not match with the Expected Output of Sample Input " + sampleInputs[counter2forTest6++] + ": " + parameters1[counter3forTest6++]);
		} catch (InstantiationException | IllegalAccessException | InvocationTargetException | NoSuchMethodException ex) {
		}
	}

	static Stream<Arguments> numbersProviderForTest7() {
		return Stream.of(
				Arguments.of(0)
			);
	}

	@ParameterizedTest
	@MethodSource({"numbersProviderForTest7"})
	@Order(7)
	@DisabledIf("customConditionForMethod")
	public void test7(int num) {
		int[] sampleInputs = {4};
		int[] parameters1 = {0};
		String[] expectedResults = {"-2"};
		
		try {
			Object classObject = operationClass.getDeclaredConstructor((Class<?>[]) new Class[0]).newInstance(new Object[0]);
			
			String actualResult = (String) operationMethod.invoke(classObject, num);
			
			assertEquals(expectedResults[counter1forTest7++], actualResult, "The result generated by the method does not match with the Expected Output of Sample Input " + sampleInputs[counter2forTest7++] + ": " + parameters1[counter3forTest7++]);
		} catch (InstantiationException | IllegalAccessException | InvocationTargetException | NoSuchMethodException ex) {
		}
	}
}